{% set name = "jupytercad-salome" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupytercad_salome-{{ version }}.tar.gz
  sha256: d129f9d05ea9692f6378e931e6be2aa39d0e256cd1a62507504a0a52d1f02fd8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - yarn
    - jupyterlab >=4,<5
    - hatch-jupyter-builder
    - hatch-nodejs-version >=0.3.2
  run:
    - python >={{ python_min }}
    - jupyter_server >=2.0.1,<3
    - jupytercad_core >=2,<3
    - jupytercad_lab >=2,<3

test:
  imports:
    - jupytercad_salome
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f ${PREFIX}/share/jupyter/labextensions/@jupytercad/jupytercad-salome/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupytercad/jupytercad-salome\\package.json (exit 1)          # [win]

about:
  home: https://github.com/jupytercad/jupytercad-salome
  summary: 'JupyterCAD plugin adding for generating meshes'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/jupytercad/jupytercad-salome

extra:
  recipe-maintainers:
    - martinRenou
    - trungleduc
