{% set name = "jupytercad-salome" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupytercad_salome-{{ version }}.tar.gz
  sha256: 10e6dbe0eb27dc1079b2f46254f2e3e6301b9a88185c9cfbef703b6a01b48a87

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
    - yarn
    - jupyterlab >=4,<5
    - hatch-jupyter-builder
    - hatch-nodejs-version >=0.3.2
  run:
    - python >=3.8
    - jupyter_server >=2.0.1,<3
    - jupytercad_core >=1,<2
    - jupytercad_lab >=1,<2

test:
  imports:
    - jupytercad_salome
  requires:
    - pip
  commands:
    - pip check
    - test -f ${PREFIX}/share/jupyter/labextensions/@jupytercad/jupytercad-salome/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupytercad/jupytercad-salome\\package.json (exit 1)          # [win]

about:
  home: https://github.com/jupytercad/jupytercad-salome
  summary: 'JupyterCAD plugin adding for generating meshes'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/jupytercad/jupytercad-salome

extra:
  recipe-maintainers:
    - martinRenou
    - trungleduc
